/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerView;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BanDoc;
import model.Sach;

/**
 *
 * @author nguye_000
 */
public class SearchView extends javax.swing.JFrame {

    /**
     * Creates new form LoginSucessKH
     */
    ObjectInputStream ios;
    ObjectOutputStream oos;
    DataInputStream dataIn;
    DataOutputStream dataOut;
    Socket socket;
     private DefaultTableModel dtmBook;
     private DefaultTableModel dtmBook1;
    private int selectedIndex = -1;
    private BanDoc ac;
    private ArrayList<Sach> listSach= new ArrayList<>();
    private ArrayList<Sach> result;
    private int stt=0;
    public SearchView(Socket socet,ObjectInputStream ios, ObjectOutputStream oos, DataInputStream dataIn, DataOutputStream dataOut,BanDoc ac) {
        setVisible(true);
        initComponents();
         myInit();
        myInit1();
        this.ios = ios;
        this.oos = oos;
        this.socket = socet;
        this.dataIn = dataIn;
        this.dataOut = dataOut;
        this.ac=ac;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KHSuccess = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMuon = new javax.swing.JTable();
        btnMuon = new javax.swing.JButton();
        message = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSearch.setText("Nhập tên sách, tác giả");

        btnTimKiem.setText("Search");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        TableMuon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "ID", "Name", "Author"
            }
        ));
        TableMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMuonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMuon);
        if (TableMuon.getColumnModel().getColumnCount() > 0) {
            TableMuon.getColumnModel().getColumn(0).setHeaderValue("Stt");
            TableMuon.getColumnModel().getColumn(1).setHeaderValue("ID");
            TableMuon.getColumnModel().getColumn(2).setHeaderValue("Name");
            TableMuon.getColumnModel().getColumn(3).setHeaderValue("Author");
        }

        btnMuon.setText("Borrow");
        btnMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messageLayout = new javax.swing.GroupLayout(message);
        message.setLayout(messageLayout);
        messageLayout.setHorizontalGroup(
            messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        messageLayout.setVerticalGroup(
            messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        tbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "ID", "Name", "Author"
            }
        ));
        jScrollPane2.setViewportView(tbl2);

        javax.swing.GroupLayout KHSuccessLayout = new javax.swing.GroupLayout(KHSuccess);
        KHSuccess.setLayout(KHSuccessLayout);
        KHSuccessLayout.setHorizontalGroup(
            KHSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KHSuccessLayout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addGroup(KHSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KHSuccessLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMuon)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addGap(344, 344, 344))
            .addGroup(KHSuccessLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnTimKiem)
                .addGap(203, 203, 203))
        );
        KHSuccessLayout.setVerticalGroup(
            KHSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KHSuccessLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KHSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KHSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTimKiem))
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(KHSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnReset)
                    .addComponent(btnMuon))
                .addGap(211, 211, 211))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(KHSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(KHSuccess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonActionPerformed
        // TODO add your handling code here:
        BorrowView  borrowView = new BorrowView(socket,ios, oos,dataIn,dataOut,listSach,ac);
        setVisible(false);
       
    }//GEN-LAST:event_btnMuonActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtSearch.setText("");
       // TableMuon.setRo
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        
         String Tk = txtSearch.getText();
        System.out.println(""+chuanHoa(Tk));
        try {
             dataOut.writeUTF(chuanHoa(Tk));// gui thong tin nhap vao ve server
             result =  (ArrayList<Sach>) ios.readObject();
             if(result != null ){
                 Search se = new Search(socket,ios, oos,dataIn,dataOut,ac,result);
             }else{
                 JOptionPane.showMessageDialog(message, "Thong tin tim kiem khong ton tai");
        }
        } catch (IOException ex) {
            Logger.getLogger(SearchView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
            // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void TableMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMuonMouseClicked
        // TODO add your handling code here:
     selectedIndex = TableMuon.getSelectedRow();
    if (selectedIndex!=-1) {
    stt++;
    if(stt<=5){
        dtmBook1.addRow(new Object[]{
        Integer.toString(stt),
        dtmBook.getValueAt(selectedIndex,1).toString(),
        dtmBook.getValueAt(selectedIndex,2).toString(),
        dtmBook.getValueAt(selectedIndex,3).toString()
    });
       for(int i=0; i<result.size(); i++){
           Sach s= result.get(i);
           if(s.getMaSach().equalsIgnoreCase(dtmBook.getValueAt(selectedIndex, 1).toString())){
               listSach.add(s);
           }
       } 
    }else{
        JOptionPane.showMessageDialog(message, "ban da chon qua so sach quy dinh"); 
    }
    }             
    }//GEN-LAST:event_TableMuonMouseClicked
private void handleReturnData(ArrayList<Sach> result) {
        DefaultTableModel model = (DefaultTableModel) TableMuon.getModel();//xuat ra tabe
        model.getDataVector().clear();
        if (null != result) {
            for(int j=0; j<result.size(); j++){
                Sach sach = result.get(j);
            model.addRow(new Object[]{j+1, sach.getMaSach(), sach.getTenSach(),sach.getTacGia()}); 
            }
        }
    }
  public static String chuanHoa(String s) {
        String x = s.toLowerCase().trim().replaceAll("\\s+", " ");
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KHSuccess;
    private javax.swing.JTable TableMuon;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMuon;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel message;
    private javax.swing.JTable tbl2;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

private void myInit() {
        dtmBook = (DefaultTableModel) TableMuon.getModel();
        TableMuon.setModel(dtmBook);
        setLocationRelativeTo(null);
    }
 private void myInit1() {   
        dtmBook1 = (DefaultTableModel) tbl2.getModel();
        tbl2.setModel(dtmBook1);
        setLocationRelativeTo(null);
    }
}
